### ISSUE TITLE
Should not rise KeyError if not a valid for Enum

### ISSUE THREAD

**Issue by pskd73** [pskd73/pydictable#21]
```python
class CustomerType(Enum):
    regular = 'reg'
    premium = 'pre'
    vip = 3

class Customer(DictAble):
    type: CustomerType

Customer(dict={'type': 'aksd'})
```

Gives following error
```
Error
Traceback (most recent call last):
  File "/Users/pskd73/pydictable/pydictable/test_core.py", line 593, in test_enum_with_type_hints
    Customer(dict={'type': 'aksd'})
  File "/Users/pskd73/pydictable/pydictable/core.py", line 29, in __init__
    self.__validate_dict(kwargs['dict'])
  File "/Users/pskd73/pydictable/pydictable/core.py", line 82, in __validate_dict
    field.validate_dict(attr, value)
  File "/Users/pskd73/pydictable/pydictable/field.py", line 183, in validate_dict
    self.enum[v] if self.is_name else self.enum(v)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'aksd'
```

It should ideally give DataValidationError if it gets invalid value

**Comment by SAMSAX639** [comment]
This issue is fixed and is release in version 0.11.1
